apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: location-service
  template:
    metadata:
      labels:
        app: location-service
    spec:
      containers:
        - name: location-service
          image: simonshub/udaconnect-ms-location-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: POSTGRES_PASSWORD
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: POSTGRES_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: POSTGRES_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: POSTGRES_DB
            - name: KAFKA_SERVER
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: KAFKA_SERVER                       
            - name: KAFKA_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: KAFKA_TOPIC       
            - name: KAFKA_GROUP_ID
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: KAFKA_GROUP_ID 
            - name: CYCLE_TIME
              valueFrom:
                configMapKeyRef:
                  name: udaconnect-env
                  key: CYCLE_TIME_LOCATION 