apiVersion: v1
kind: Service
metadata:
  name: kafka-svc
spec:
  type: ClusterIP
  selector:
    app: kafka
  ports:
  - name: internal
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: external
    port: 9094
    protocol: TCP
    targetPort: 9094