kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-volume
spec:
  storageClassName: manual
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/data/postgres
