apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: configuration
  namespace: argocd
spec:
  destination:
    namespace: udaconnect
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/configuration
    repoURL: git@github.com:simonjanssen/Projects.UdaConnect.git
    targetRevision: feature/argocd/postgres
  syncPolicy: {}