apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: exposure-service
  namespace: argocd
spec:
  destination:
    namespace: udaconnect
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/exposure-service
    repoURL: git@github.com:simonjanssen/Projects.UdaConnect.git
    targetRevision: feature/argocd
  syncPolicy: {}