apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: location-api
  namespace: argocd
spec:
  destination:
    namespace: udaconnect
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/location-api
    repoURL: git@github.com:simonjanssen/Projects.UdaConnect.git
    targetRevision: feature/argocd
  syncPolicy: {}