apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pgadmin
  namespace: argocd
spec:
  destination:
    namespace: udaconnect
    server: https://kubernetes.default.svc
  project: default
  source:
    path: manifests/pgadmin
    repoURL: git@github.com:simonjanssen/Projects.UdaConnect.git
    targetRevision: dev
  syncPolicy: {}