name: UdaConnect Application Build

on:
  pull_request:
    branches:
      - dev

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: print variables
        run: |
          echo "github.head_ref = ${{ github.head_ref }}"
          echo "github.ref = ${{ github.ref }}"
          echo "github.ref_name = ${{ github.ref_name }}"
      - name: clone github repository
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          ref: ${{ env.GITHUB_REF }}
