name: UdaConnect Application Build

on:
  pull_request:
    branches:
      - dev

jobs:
  build_and_push:
    if: startsWith(github.head_ref, 'app/')
    runs-on: ubuntu-latest
    steps:
      - name: Clone github repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.head_ref }}
      - name: Get application name
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        id: appname
        run: |
          echo "NAME=$(echo ${{ github.head_ref }} | cut -d'/' -f2)" >> $GITHUB_OUTPUT
      - name: Get application tag
        id: apptag
        run: |
          echo "TAG=$(cat applications/${{ steps.appname.outputs.NAME }}/VERSION)" >> $GITHUB_OUTPUT 
      - name: Print variables
        run: |
          echo "${{ steps.appname.outputs.NAME }}"
          echo "${{ steps.apptag.outputs.TAG }}"
      - name: Copy types
        run: cp -f build/types/* applications/${{ steps.variables.outputs.APPNAME }}/
      - name: Set up qemu
        uses: docker/setup-qemu-action@v3
      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:applications/${{ steps.appname.outputs.NAME }}"
          platforms: linux/amd64
          push: True
          tags: ${{ secrets.DOCKERHUB_USER }}/${{ steps.appname.outputs.NAME }}:${{ steps.apptag.outputs.TAG }},${{ secrets.DOCKERHUB_USER }}/${{ steps.appname.outputs.NAME }}:latest
          
